// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_high_scores = "CgkIlu2Nm5MWEAIQCQ"; // <GPGSID>
        public const string achievement_infinite = "CgkIlu2Nm5MWEAIQBg"; // <GPGSID>
        public const string achievement_astral_sines = "CgkIlu2Nm5MWEAIQAw"; // <GPGSID>
        public const string achievement_to_understand = "CgkIlu2Nm5MWEAIQAQ"; // <GPGSID>
        public const string achievement_dance_of_the_cosmic_serpents = "CgkIlu2Nm5MWEAIQBA"; // <GPGSID>
        public const string achievement_singularity = "CgkIlu2Nm5MWEAIQBQ"; // <GPGSID>
        public const string achievement_cosmic_balance = "CgkIlu2Nm5MWEAIQAg"; // <GPGSID>
        public const string leaderboard_high_scores_previous_season = "CgkIlu2Nm5MWEAIQBw"; // <GPGSID>

}

